# Customer Retention & Marketing Performance Analytics

In [ ]:
# This notebook performs an initial data quality assessment of the customer dataset, including checks
#for missing values, duplicates, data types, invalid values, date inconsistencies, and potential outliers.

## 1. Data Loading & Initial Inspection

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\hp\Downloads\Sales_Marketing_Dataset\Sales - Marketing customer dataset.csv")

In [3]:
df.shape

(15000, 30)

In [4]:
df.head()

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,support_tickets,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
0,10001,Male,52.0,India,Berlin,2022-05-10 00:00:00,2024-12-31 00:00:00,Email,Tablet,Annual,...,0,0,3,UPI,3.0,10,27.56,915.310827,14,0
1,10002,NaN,35.0,Germany,Mumbai,2024-06-16 00:00:00,2024-05-07 00:00:00,Organic,Desktop,Monthly,...,5,0,3,BKash,3.0,7,15.15,2079.960938,11,0
2,10003,Female,27.0,Germany,London,2023-08-23 00:00:00,2024-04-28 00:00:00,Email,Mobile,Annual,...,1,0,2,UPI,5.0,6,13.51,1379.150885,9,0
3,10004,Female,36.0,India,Mumbai,2024-01-28 00:00:00,2023-05-20 00:00:00,Facebook Ads,Tablet,Annual,...,0,0,2,PayPal,4.0,6,25.65,774.652684,7,0
4,10005,Male,29.0,USA,Hamburg,2023-07-21 00:00:00,2024-04-07 00:00:00,Referral,Mobile,Monthly,...,2,1,4,BKash,3.0,1,12.39,87.680409,11,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 30 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   customer_id                 15000 non-null  int64
 1   gender                      14262 non-null  object
 2   age                         13800 non-null  float64
 3   country                     15000 non-null  object
 4   city                        15000 non-null  object
 5   signup_date                 15000 non-null  object
 6   last_purchase_date          15000 non-null  object
 7   acquisition_channel         15000 non-null  object
 8   device_type                 15000 non-null  object
 9   subscription_type           15000 non-null  object
 10  is_premium_user             15000 non-null  int64
 11  total_visits                15000 non-null  int64
 12  avg_session_time            15000 non-null  float64
 13  pages_per_session           15000 non-null  float64
 14  email_open_rate             15000 non-null  float64
 15  email_click_rate            15000 non-null  float64
 16  total_spent                 13950 non-null  float64
 17  avg_order_value             15000 non-null  float64
 18  discount_used               15000 non-null  int64
 19  coupon_code                 8867 non-null   object
 20  support_tickets             15000 non-null  int64
 21  refund_requested            15000 non-null  int64
 22  delivery_delay_days         15000 non-null  int64
 23  payment_method              15000 non-null  object
 24  satisfaction_score          14298 non-null  float64
 25  nps_score                   15000 non-null  int64
 26  marketing_spend_per_user    15000 non-null  float64
 27  lifetime_value              15000 non-null  float64
 28  last_3_month_purchase_freq  15000 non-null  int64
 29  churn                       15000 non-null  int64
dtypes: float64(10), int64(10), object(10)
memory usage: 3.4+ MB

## 2. Data Quality Audit

In [8]:
df.isnull().sum()

customer_id                      0
gender                         738
age                           1200
country                          0
city                             0
signup_date                      0
last_purchase_date               0
acquisition_channel              0
device_type                      0
subscription_type                0
is_premium_user                  0
total_visits                     0
avg_session_time                 0
pages_per_session                0
email_open_rate                  0
email_click_rate                 0
total_spent                   1050
avg_order_value                  0
discount_used                    0
coupon_code                   6133
support_tickets                  0
refund_requested                 0
delivery_delay_days              0
payment_method                   0
satisfaction_score             702
nps_score                        0
marketing_spend_per_user         0
lifetime_value                   0
last_3_month_purchase_freq       0
churn                            0
dtype: int64

In [9]:
df.isnull().mean()*100

customer_id                    0.000000
gender                         4.920000
age                            8.000000
country                        0.000000
city                           0.000000
signup_date                    0.000000
last_purchase_date             0.000000
acquisition_channel            0.000000
device_type                    0.000000
subscription_type              0.000000
is_premium_user                0.000000
total_visits                   0.000000
avg_session_time               0.000000
pages_per_session              0.000000
email_open_rate                0.000000
email_click_rate               0.000000
total_spent                    7.000000
avg_order_value                0.000000
discount_used                  0.000000
coupon_code                   40.886667
support_tickets                0.000000
refund_requested               0.000000
delivery_delay_days            0.000000
payment_method                 0.000000
satisfaction_score             4.680000
nps_score                      0.000000
marketing_spend_per_user       0.000000
lifetime_value                 0.000000
last_3_month_purchase_freq     0.000000
churn                          0.000000
dtype: float64

In [10]:
missing = pd.DataFrame({
    'missing_count': df.isnull().sum(),
    'missing_percent': df.isnull().mean() * 100
})

missing[missing['missing_count'] > 0].sort_values(
    'missing_percent',
    ascending=False
)

                    missing_count  missing_percent
coupon_code                  6133        40.886667
age                          1200         8.000000
total_spent                  1050         7.000000
gender                        738         4.920000
satisfaction_score            702         4.680000

In [ ]:
# Missing Value Analysis
This check identifies columns containing missing values and measures the percentage of missing data in each column.

In [ ]:
# Duplicates

# Duplicate Check

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['customer_id'].duplicated().sum()

np.int64(0)

 # Categorical Data Validation

# Customer & Location Variables

In [13]:
df['gender'].value_counts(dropna=False)

gender
Male      6844
Female    6686
NaN        738
Other      732
Name: count, dtype: int64

In [14]:
df['country'].value_counts(dropna=False)

country
Germany       3072
India         3014
Bangladesh    2984
USA           2975
UK            2955
Name: count, dtype: int64

In [15]:
df['city'].value_counts(dropna=False)

city
London      2236
Mumbai      2184
Dhaka       2178
New York    2135
Delhi       2128
Berlin      2075
Hamburg     2064
Name: count, dtype: int64

# Marketing & Subscription Variables

In [16]:
df['acquisition_channel'].value_counts(dropna=False)

acquisition_channel
Organic         3055
Google Ads      3047
Facebook Ads    3024
Referral        2941
Email           2933
Name: count, dtype: int64

In [17]:
df['device_type'].value_counts(dropna=False)

device_type
Tablet     5043
Mobile     4997
Desktop    4960
Name: count, dtype: int64

In [18]:
df['subscription_type'].value_counts(dropna=False)

subscription_type
Monthly    7666
Annual     7334
Name: count, dtype: int64

In [19]:
df['payment_method'].value_counts(dropna=False)

payment_method
UPI       3105
PayPal    3005
SEPA      2986
BKash     2971
Card      2933
Name: count, dtype: int64

In [20]:
df['coupon_code'].value_counts(dropna=False)

coupon_code
NaN       6133
REF10     2995
SALE15    2986
NEW20     2886
Name: count, dtype: int64

# Binary Variables

In [21]:
df['is_premium_user'].value_counts(dropna=False)

is_premium_user
0    10433
1     4567
Name: count, dtype: int64

In [22]:
df['discount_used'].value_counts(dropna=False)

discount_used
0    7583
1    7417
Name: count, dtype: int64

In [23]:
df['refund_requested'].value_counts(dropna=False)

refund_requested
0    12785
1     2215
Name: count, dtype: int64

# Churn distribution

In [24]:
df['churn'].value_counts(dropna=False)

churn
0    12702
1     2298
Name: count, dtype: int64

In [25]:
df['churn'].value_counts(normalize=True) * 100

churn
0    84.68
1    15.32
Name: proportion, dtype: float64

# Date Quality Validation

In [26]:
df[['signup_date', 'last_purchase_date']].head(10)

           signup_date   last_purchase_date
0  2022-05-10 00:00:00  2024-12-31 00:00:00
1  2024-06-16 00:00:00  2024-05-07 00:00:00
2  2023-08-23 00:00:00  2024-04-28 00:00:00
3  2024-01-28 00:00:00  2023-05-20 00:00:00
4  2023-07-21 00:00:00  2024-04-07 00:00:00
5  2024-05-08 00:00:00  2023-01-20 00:00:00
6  2022-01-04 00:00:00  2023-12-05 00:00:00
7  2023-05-11 00:00:00  2024-02-14 00:00:00
8  2023-01-14 00:00:00  2024-08-19 00:00:00
9  2022-12-22 00:00:00  2024-09-04 00:00:00

In [27]:
pd.to_datetime(df['signup_date'], errors='coerce').isna().sum()

np.int64(0)

In [28]:
pd.to_datetime(df['last_purchase_date'], errors='coerce').isna().sum()

np.int64(0)

In [29]:
signup = pd.to_datetime(df['signup_date'])
purchase = pd.to_datetime(df['last_purchase_date'])

(purchase < signup).sum()

np.int64(3762)

In [30]:
df.describe()

,customer_id,age,is_premium_user,total_visits,avg_session_time,pages_per_session,email_open_rate,email_click_rate,total_spent,avg_order_value,discount_used,support_tickets,refund_requested,delivery_delay_days,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
count,15000.000000,13800.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,13950.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,14298.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,17500.500000,35.203913,0.304467,15.000933,8.020805,4.002901,0.496278,0.251231,524.357397,60.080882,0.494467,1.995600,0.147667,2.981333,3.588754,4.968667,17.575238,1235.698200,6.975133,0.153200
std,4330.271354,10.334384,0.460197,3.892704,2.991499,1.479846,0.290108,0.144689,467.050070,24.746203,0.499986,1.421214,0.354781,1.720537,1.088703,3.155495,7.183437,657.521849,4.323443,0.360192
min,10001.000000,-4.000000,0.000000,3.000000,0.006095,0.007845,0.000000,0.000000,0.267291,0.071596,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,5.000000,0.368886,0.000000,0.000000
25%,13750.750000,28.000000,0.000000,12.000000,5.974555,2.989150,0.240000,0.130000,300.432074,43.032470,0.000000,1.000000,0.000000,2.000000,3.000000,2.000000,11.380000,741.301251,3.000000,0.000000
50%,17500.500000,35.000000,0.000000,15.000000,7.991907,3.996992,0.500000,0.250000,498.843859,60.108827,0.000000,2.000000,0.000000,3.000000,4.000000,5.000000,17.630000,1216.210685,7.000000,0.000000
75%,21250.250000,42.000000,1.000000,18.000000,10.059986,5.014406,0.750000,0.380000,702.396635,76.888445,1.000000,3.000000,0.000000,4.000000,4.000000,8.000000,23.770000,1677.860399,11.000000,0.000000
max,25000.000000,95.000000,1.000000,31.000000,19.123716,10.843172,1.000000,0.500000,15910.431879,154.554696,1.000000,9.000000,1.000000,11.000000,5.000000,10.000000,30.000000,3767.490455,14.000000,1.000000

# Age validation

In [31]:
df[df['age'] < 0][['customer_id', 'age']]

       customer_id  age
3336         13337 -1.0
7848         17849 -4.0
10668        20669 -2.0

In [32]:
df['age'].sort_values().head(20)

7848    -4.0
10668   -2.0
3336    -1.0
12785    0.0
3732     2.0
10532    2.0
6388     2.0
8026     2.0
2828     2.0
2755     2.0
9595     3.0
8407     3.0
3482     4.0
13951    4.0
1714     4.0
2116     5.0
1756     5.0
14858    5.0
13612    5.0
6068     5.0
Name: age, dtype: float64

In [33]:
df[df['age'] < 18]['age'].value_counts().sort_index()

age
-4.0       1
-2.0       1
-1.0       1
 0.0       1
 2.0       6
 3.0       2
 4.0       3
 5.0       8
 6.0       9
 7.0      15
 8.0       9
 9.0      17
 10.0     22
 11.0     31
 12.0     43
 13.0     45
 14.0     44
 15.0     76
 16.0     79
 17.0    103
Name: count, dtype: int64

In [34]:
df[df['age'] > 80]['age'].value_counts().sort_index()

age
95.0    30
Name: count, dtype: int64

In [ ]:
 # Finding: Invalid ages including negative values and zero were identified.
 # These values require treatment during the data cleaning stage.

# Range and Potential Outlier Checks

 # Spending Variables

In [35]:
df['total_spent'].sort_values(ascending=False).head(20)

12992    15910.431879
5428     14954.745790
13147    14308.484729
14072    14230.702924
5593     13709.765484
12211    12259.188715
6470     10925.990676
13504    10708.427608
1192      9897.033086
11149     9049.788178
1108      8710.485502
2325      8529.704953
657       8182.490684
10625     7476.552498
3646      7364.567169
2647      6868.734872
9267      6010.208457
8099      5391.050008
6270      4931.550479
673       4433.804841
Name: total_spent, dtype: float64

In [36]:
df[df['total_spent'] > 5000]['total_spent'].count()

np.int64(18)

In [37]:
df['avg_order_value'].sort_values(ascending=False).head(20)

5145     154.554696
12259    151.107638
8052     150.199147
10405    149.740362
7436     149.353220
108      149.111471
6768     148.607026
9552     148.081160
12071    147.060534
1589     143.279001
1204     142.131937
8288     140.922215
9943     139.891637
892      139.842568
438      138.793962
11444    138.783502
7819     137.849843
7466     136.723385
12719    136.629701
5158     135.598997
Name: avg_order_value, dtype: float64

In [38]:
df[df['avg_order_value'] > 100]['avg_order_value'].count()

np.int64(835)

In [49]:
df['lifetime_value'].describe()

count    15000.000000
mean      1235.698200
std        657.521849
min          0.368886
25%        741.301251
50%       1216.210685
75%       1677.860399
max       3767.490455
Name: lifetime_value, dtype: float64

# Customer Experience Variables

In [39]:
df['delivery_delay_days'].sort_values().head(20)

5196     0
9752     0
7304     0
12053    0
9751     0
746      0
7318     0
12065    0
7337     0
7343     0
7350     0
9719     0
9701     0
4127     0
7372     0
13567    0
767      0
769      0
7406     0
2859     0
Name: delivery_delay_days, dtype: int64

In [40]:
df['support_tickets'].value_counts().sort_index()

support_tickets
0    2071
1    4047
2    4069
3    2653
4    1351
5     566
6     164
7      63
8      13
9       3
Name: count, dtype: int64

In [41]:
df['satisfaction_score'].value_counts(dropna=False).sort_index()

satisfaction_score
1.0     753
2.0    1455
3.0    3739
4.0    5323
5.0    3028
NaN     702
Name: count, dtype: int64

In [42]:
df['nps_score'].value_counts().sort_index()

nps_score
0     1370
1     1346
2     1417
3     1402
4     1388
5     1303
6     1386
7     1350
8     1356
9     1357
10    1325
Name: count, dtype: int64

# Engagement Variables

In [43]:
df['email_open_rate'].describe()

count    15000.000000
mean         0.496278
std          0.290108
min          0.000000
25%          0.240000
50%          0.500000
75%          0.750000
max          1.000000
Name: email_open_rate, dtype: float64

In [44]:
df['email_click_rate'].describe()

count    15000.000000
mean         0.251231
std          0.144689
min          0.000000
25%          0.130000
50%          0.250000
75%          0.380000
max          0.500000
Name: email_click_rate, dtype: float64

In [45]:
df['pages_per_session'].describe()

count    15000.000000
mean         4.002901
std          1.479846
min          0.007845
25%          2.989150
50%          3.996992
75%          5.014406
max         10.843172
Name: pages_per_session, dtype: float64

In [46]:
df['avg_session_time'].describe()

count    15000.000000
mean         8.020805
std          2.991499
min          0.006095
25%          5.974555
50%          7.991907
75%         10.059986
max         19.123716
Name: avg_session_time, dtype: float64

# Marketing Variable

In [47]:
df['marketing_spend_per_user'].describe()

count    15000.000000
mean        17.575238
std          7.183437
min          5.000000
25%         11.380000
50%         17.630000
75%         23.770000
max         30.000000
Name: marketing_spend_per_user, dtype: float64

# Data Quality Summary

In [ ]:
Key findings from the data quality audit:
1) Missing values were identified in selected columns.
2) No/identified duplicate records were checked at both row and customer ID level.
3) Invalid age values, including negative values and zero, were identified.
4) Date columns were validated for conversion and logical consistency.
5) Numerical variables were reviewed for unusual ranges and potential outliers. 
Next step: These issues will be addressed in the Data Cleaning notebook before performing exploratory data analysis