# Customer Retention & Marketing Performance Analytics

# Data Cleaning

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv(r"C:\Users\hp\Downloads\Sales_Marketing_Dataset\Sales - Marketing customer dataset.csv")

In [3]:
df.shape

(15000, 30)

In [4]:
df.head()

,customer_id,gender,age,country,city,signup_date,last_purchase_date,acquisition_channel,device_type,subscription_type,...,support_tickets,refund_requested,delivery_delay_days,payment_method,satisfaction_score,nps_score,marketing_spend_per_user,lifetime_value,last_3_month_purchase_freq,churn
0,10001,Male,52.0,India,Berlin,2022-05-10 00:00:00,2024-12-31 00:00:00,Email,Tablet,Annual,...,0,0,3,UPI,3.0,10,27.56,915.310827,14,0
1,10002,NaN,35.0,Germany,Mumbai,2024-06-16 00:00:00,2024-05-07 00:00:00,Organic,Desktop,Monthly,...,5,0,3,BKash,3.0,7,15.15,2079.960938,11,0
2,10003,Female,27.0,Germany,London,2023-08-23 00:00:00,2024-04-28 00:00:00,Email,Mobile,Annual,...,1,0,2,UPI,5.0,6,13.51,1379.150885,9,0
3,10004,Female,36.0,India,Mumbai,2024-01-28 00:00:00,2023-05-20 00:00:00,Facebook Ads,Tablet,Annual,...,0,0,2,PayPal,4.0,6,25.65,774.652684,7,0
4,10005,Male,29.0,USA,Hamburg,2023-07-21 00:00:00,2024-04-07 00:00:00,Referral,Mobile,Monthly,...,2,1,4,BKash,3.0,1,12.39,87.680409,11,0

## 1. Handling Missing Values

### Numerical Missing Values

In [5]:
df['age'].isnull().sum()

np.int64(1200)

In [6]:
df['age'].median()

35.0

In [7]:
df['age'] = df['age'].fillna(df['age'].median())

In [8]:
df['age'].isnull().sum()

np.int64(0)

In [13]:
df['total_spent'].median()

498.84385906874195

In [14]:
df['total_spent'] = df['total_spent'].fillna(df['total_spent'].median())

In [15]:
df['total_spent'].isnull().sum()

np.int64(0)

In [20]:
df['satisfaction_score'].median()

4.0

In [21]:
df['satisfaction_score'] = df['satisfaction_score'].fillna(
    df['satisfaction_score'].median()
)

In [22]:
df['satisfaction_score'].isnull().sum()

np.int64(0)

### Categorical Missing Values

In [88]:
df['gender'].value_counts(dropna = False)

gender
Male       6844
Female     6686
Unknown     738
Other       732
Name: count, dtype: int64

In [89]:
df['gender'] = df['gender'].fillna('Unknown')

In [90]:
df['gender'].isnull().sum()

np.int64(0)

In [91]:
df['gender'].value_counts()

gender
Male       6844
Female     6686
Unknown     738
Other       732
Name: count, dtype: int64

In [92]:
df['coupon_code'].isnull().sum()

np.int64(0)

In [93]:
df['coupon_code'] = df['coupon_code'].fillna('No Coupon')

In [94]:
df['coupon_code'].value_counts()

coupon_code
No Coupon    6133
REF10        2995
SALE15       2986
NEW20        2886
Name: count, dtype: int64

In [23]:
df.isnull().sum()

customer_id                   0
gender                        0
age                           0
country                       0
city                          0
signup_date                   0
last_purchase_date            0
acquisition_channel           0
device_type                   0
subscription_type             0
is_premium_user               0
total_visits                  0
avg_session_time              0
pages_per_session             0
email_open_rate               0
email_click_rate              0
total_spent                   0
avg_order_value               0
discount_used                 0
coupon_code                   0
support_tickets               0
refund_requested              0
delivery_delay_days           0
payment_method                0
satisfaction_score            0
nps_score                     0
marketing_spend_per_user      0
lifetime_value                0
last_3_month_purchase_freq    0
churn                         0
dtype: int64

## 2. Handling Invalid Values

### Invalid Age Values

In [24]:
df[df['age']<=0][['customer_id','age']]

       customer_id  age
3336         13337 -1.0
7848         17849 -4.0
10668        20669 -2.0
12785        22786  0.0

In [25]:
df.loc[df['age'] <= 0, 'age'] = pd.NA

In [26]:
df['age'] = df['age'].fillna(df['age'].median())

In [27]:
df[df['age'] <= 0][['customer_id', 'age']]

Empty DataFrame
Columns: [customer_id, age]
Index: []

In [28]:
df[df['age'] < 15][['customer_id', 'age']]

       customer_id   age
22           10023  12.0
29           10030  12.0
41           10042  13.0
76           10077  12.0
125          10126   9.0
...            ...   ...
14858        24859   5.0
14868        24869  12.0
14881        24882  14.0
14984        24985  13.0
14993        24994  13.0

[254 rows x 2 columns]

In [29]:
df[df['age'] < 15].shape[0]

254

In [30]:
df.loc[df['age']<15,'age'] =pd.NA

In [31]:
df['age'] = df['age'].fillna(df['age'].median())

In [32]:
df['age'].min()

15.0

In [33]:
df[df['age'] == 95].shape[0]

30

In [34]:
df[df['age'] == 95][['customer_id', 'age', 'total_spent', 'total_visits', 'churn']]

       customer_id   age   total_spent  total_visits  churn
158          10159  95.0   2882.301398            12      0
657          10658  95.0   8182.490684            15      0
673          10674  95.0   4433.804841            11      0
1108         11109  95.0   8710.485502            11      0
1192         11193  95.0   9897.033086            12      0
1709         11710  95.0    498.843859            11      0
2325         12326  95.0   8529.704953            10      0
2589         12590  95.0   1811.777680            15      0
2647         12648  95.0   6868.734872            12      0
2837         12838  95.0   3814.420123            10      0
3646         13647  95.0   7364.567169             9      0
4556         14557  95.0   2462.906271            13      0
4670         14671  95.0    384.529483             9      0
5133         15134  95.0     69.820245            10      0
5428         15429  95.0  14954.745790            22      0
5593         15594  95.0  13709.765484            12      0
6270         16271  95.0   4931.550479            18      0
6470         16471  95.0  10925.990676            16      0
7435         17436  95.0   4325.673287            17      0
8099         18100  95.0   5391.050008            16      0
9267         19268  95.0   6010.208457            13      0
10625        20626  95.0   7476.552498            20      0
11149        21150  95.0   9049.788178             8      0
11643        21644  95.0   2048.042513            15      0
12211        22212  95.0  12259.188715            12      0
12881        22882  95.0   2134.698976            12      0
12992        22993  95.0  15910.431879            18      0
13147        23148  95.0  14308.484729            17      0
13504        23505  95.0  10708.427608            21      0
14072        24073  95.0  14230.702924            17      0

In [35]:
df['total_spent'].sort_values(ascending=False).head(20)

12992    15910.431879
5428     14954.745790
13147    14308.484729
14072    14230.702924
5593     13709.765484
12211    12259.188715
6470     10925.990676
13504    10708.427608
1192      9897.033086
11149     9049.788178
1108      8710.485502
2325      8529.704953
657       8182.490684
10625     7476.552498
3646      7364.567169
2647      6868.734872
9267      6010.208457
8099      5391.050008
6270      4931.550479
673       4433.804841
Name: total_spent, dtype: float64

In [36]:
df['avg_order_value'].sort_values(ascending=False).head(20)

5145     154.554696
12259    151.107638
8052     150.199147
10405    149.740362
7436     149.353220
108      149.111471
6768     148.607026
9552     148.081160
12071    147.060534
1589     143.279001
1204     142.131937
8288     140.922215
9943     139.891637
892      139.842568
438      138.793962
11444    138.783502
7819     137.849843
7466     136.723385
12719    136.629701
5158     135.598997
Name: avg_order_value, dtype: float64

In [37]:
df[df['avg_order_value'] <= 0][['customer_id', 'avg_order_value']]

Empty DataFrame
Columns: [customer_id, avg_order_value]
Index: []

In [38]:
df[df['delivery_delay_days'] < 0][['customer_id', 'delivery_delay_days']]

Empty DataFrame
Columns: [customer_id, delivery_delay_days]
Index: []

In [39]:
df[df['support_tickets'] < 0][['customer_id', 'support_tickets']]

Empty DataFrame
Columns: [customer_id, support_tickets]
Index: []

In [40]:
df[(df['satisfaction_score'] < 1) | (df['satisfaction_score'] > 5)][
    ['customer_id', 'satisfaction_score']
]

Empty DataFrame
Columns: [customer_id, satisfaction_score]
Index: []

In [41]:
df[(df['nps_score'] < 0) | (df['nps_score'] > 10)][
    ['customer_id', 'nps_score']
]

Empty DataFrame
Columns: [customer_id, nps_score]
Index: []

### Invalid Numerical Values

In [42]:
numeric_cols = [
    'email_open_rate',
    'email_click_rate',
    'pages_per_session',
    'avg_session_time',
    'marketing_spend_per_user',
    'lifetime_value',
    'last_3_month_purchase_freq',
    'churn',
    'is_premium_user',
    'discount_used',
    'refund_requested'
]

for col in numeric_cols:
    print(f"\n{col}")
    print(df[df[col] < 0][['customer_id', col]])

email_open_rate
Empty DataFrame
Columns: [customer_id, email_open_rate]
Index: []

email_click_rate
Empty DataFrame
Columns: [customer_id, email_click_rate]
Index: []

pages_per_session
Empty DataFrame
Columns: [customer_id, pages_per_session]
Index: []

avg_session_time
Empty DataFrame
Columns: [customer_id, avg_session_time]
Index: []

marketing_spend_per_user
Empty DataFrame
Columns: [customer_id, marketing_spend_per_user]
Index: []

lifetime_value
Empty DataFrame
Columns: [customer_id, lifetime_value]
Index: []

last_3_month_purchase_freq
Empty DataFrame
Columns: [customer_id, last_3_month_purchase_freq]
Index: []

churn
Empty DataFrame
Columns: [customer_id, churn]
Index: []

is_premium_user
Empty DataFrame
Columns: [customer_id, is_premium_user]
Index: []

discount_used
Empty DataFrame
Columns: [customer_id, discount_used]
Index: []

refund_requested
Empty DataFrame
Columns: [customer_id, refund_requested]
Index: []

In [43]:
for col in ['email_open_rate', 'email_click_rate']:
    print(f"\n{col}")
    print(df[(df[col] < 0) | (df[col] > 1)][['customer_id', col]])

email_open_rate
Empty DataFrame
Columns: [customer_id, email_open_rate]
Index: []

email_click_rate
Empty DataFrame
Columns: [customer_id, email_click_rate]
Index: []

### Invalid Binary Values

In [44]:
binary_cols = [
    'is_premium_user',
    'discount_used',
    'refund_requested',
    'churn'
]

for col in binary_cols:
    print(f"\n{col}")
    print(df[~df[col].isin([0, 1])][['customer_id', col]])

is_premium_user
Empty DataFrame
Columns: [customer_id, is_premium_user]
Index: []

discount_used
Empty DataFrame
Columns: [customer_id, discount_used]
Index: []

refund_requested
Empty DataFrame
Columns: [customer_id, refund_requested]
Index: []

churn
Empty DataFrame
Columns: [customer_id, churn]
Index: []

In [45]:
count_cols = [
    'total_visits',
    'last_3_month_purchase_freq',
    'pages_per_session'
]

for col in count_cols:
    print(f"\n{col}")
    print(df[df[col] <= 0][['customer_id', col]])

total_visits
Empty DataFrame
Columns: [customer_id, total_visits]
Index: []

last_3_month_purchase_freq
       customer_id  last_3_month_purchase_freq
13           10014                           0
26           10027                           0
39           10040                           0
40           10041                           0
47           10048                           0
...            ...                         ...
14955        24956                           0
14960        24961                           0
14973        24974                           0
14994        24995                           0
14996        24997                           0

[1018 rows x 2 columns]

pages_per_session
Empty DataFrame
Columns: [customer_id, pages_per_session]
Index: []

## 3. Handling Potential Outliers

### Outlier Detection Using IQR

In [46]:
Q1 = df['total_spent'].quantile(0.25)
Q3 = df['total_spent'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 317.255561908933
Q3: 683.7815083157315
IQR: 366.5259464067985
Lower: -232.53335770126472
Upper: 1233.5704279259292

In [47]:
df[df['total_spent'] > upper][['customer_id', 'total_spent']]

       customer_id  total_spent
158          10159  2882.301398
259          10260  1329.511361
487          10488  1296.850588
636          10637  1255.661112
657          10658  8182.490684
...            ...          ...
14122        24123  1313.831411
14272        24273  1302.648962
14423        24424  1268.266795
14785        24786  1345.625938
14938        24939  1238.958705

[119 rows x 2 columns]

In [48]:
Q1 = df['avg_order_value'].quantile(0.25)
Q3 = df['avg_order_value'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 43.032469870895476
Q3: 76.88844515132007
IQR: 33.855975280424595
Lower: -7.75149304974142
Upper: 127.67240807195697

In [49]:
df[df['avg_order_value'] > upper][['customer_id', 'avg_order_value']]

       customer_id  avg_order_value
108          10109       149.111471
438          10439       138.793962
686          10687       130.425006
892          10893       139.842568
1204         11205       142.131937
1389         11390       130.566118
1520         11521       128.492199
1589         11590       143.279001
1697         11698       128.757874
2952         12953       131.287994
3058         13059       134.390485
3181         13182       129.581817
3892         13893       128.964095
4521         14522       130.457753
4663         14664       134.108453
4718         14719       130.183524
5145         15146       154.554696
5158         15159       135.598997
5465         15466       129.908010
5783         15784       130.336938
6712         16713       130.684648
6768         16769       148.607026
7336         17337       130.822962
7395         17396       128.763535
7436         17437       149.353220
7466         17467       136.723385
7819         17820       137.849843
7907         17908       133.954437
7985         17986       133.729390
8052         18053       150.199147
8288         18289       140.922215
9189         19190       128.256560
9552         19553       148.081160
9719         19720       131.671286
9888         19889       133.197450
9943         19944       139.891637
10405        20406       149.740362
11024        21025       130.367484
11198        21199       129.964079
11335        21336       135.141591
11444        21445       138.783502
11453        21454       131.587470
11797        21798       134.981735
12071        22072       147.060534
12259        22260       151.107638
12293        22294       131.722043
12544        22545       131.405144
12595        22596       133.700669
12719        22720       136.629701
12786        22787       129.709980
13042        23043       128.100239
13645        23646       131.955230
14388        24389       134.281017
14441        24442       131.047198

In [50]:
Q1 = df['pages_per_session'].quantile(0.25)
Q3 = df['pages_per_session'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 2.98914955880416
Q3: 5.014405922706993
IQR: 2.0252563639028325
Lower: -0.04873498705008883
Upper: 8.052290468561242

In [51]:
df[
    (df['pages_per_session'] < lower) |
    (df['pages_per_session'] > upper)
][['customer_id', 'pages_per_session']]

       customer_id  pages_per_session
533          10534           8.286402
603          10604           8.486126
624          10625           8.692866
707          10708           8.510910
884          10885           8.867683
1286         11287           8.446466
1596         11597           8.850111
1604         11605           8.138241
3014         13015           8.330131
3978         13979           9.197071
4480         14481           8.305139
4911         14912          10.843172
4941         14942           8.095061
5370         15371           8.253378
6316         16317           8.496814
7064         17065           8.305557
8341         18342           8.082784
9036         19037           8.728626
9545         19546           8.320563
9643         19644           9.497844
9905         19906           8.332134
10120        20121           8.089526
10510        20511           8.447430
10872        20873           8.234773
10919        20920           8.187868
11032        21033           8.110937
12082        22083           8.936190
12089        22090           8.370816
12272        22273           8.100914
12330        22331           8.536140
12931        22932           8.780253
14677        24678           9.429979
14971        24972           8.313819

In [52]:
df[
    (df['pages_per_session'] < lower) |
    (df['pages_per_session'] > upper)
    ].shape[0]

33

In [53]:
Q1 = df['avg_session_time'].quantile(0.25)
Q3 = df['avg_session_time'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 5.9745545092993675
Q3: 10.05998559213775
IQR: 4.085431082838382
Lower: -0.15359211495820535
Upper: 16.188132216395324

In [54]:
df[
    (df['avg_session_time'] < lower) |
    (df['avg_session_time'] > upper)
][['customer_id', 'avg_session_time']]

       customer_id  avg_session_time
2306         12307         17.247894
3124         13125         16.447258
3830         13831         16.352969
3840         13841         17.185633
3901         13902         16.393011
4042         14043         16.647194
4058         14059         17.858533
4192         14193         16.238087
4273         14274         17.713778
5178         15179         16.974225
5312         15313         16.307046
5376         15377         16.788268
5547         15548         16.855345
5958         15959         16.772680
6626         16627         17.004620
6627         16628         16.269623
6638         16639         16.310411
6655         16656         16.524776
7727         17728         16.862079
8379         18380         17.045869
8389         18390         17.054198
8459         18460         16.441570
8631         18632         16.466161
8640         18641         18.852387
9058         19059         17.593381
9100         19101         16.226138
9747         19748         16.844840
10145        20146         16.826521
10280        20281         16.383915
10527        20528         16.275360
10931        20932         16.494141
11002        21003         17.618532
12022        22023         17.152997
12269        22270         18.155786
12336        22337         17.275977
12550        22551         16.290237
12704        22705         19.123716
12911        22912         17.420298
12964        22965         16.236335
13049        23050         16.620794
13961        23962         16.260327
14150        24151         16.484569
14548        24549         17.671881
14577        24578         16.338415
14679        24680         16.760689

In [55]:
df[
    (df['avg_session_time'] < lower) |
    (df['avg_session_time'] > upper)
].shape[0]

45

In [56]:
Q1 = df['marketing_spend_per_user'].quantile(0.25)
Q3 = df['marketing_spend_per_user'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 11.38
Q3: 23.77
IQR: 12.389999999999999
Lower: -7.2049999999999965
Upper: 42.355

In [57]:
df[
    (df['marketing_spend_per_user'] < lower) |
    (df['marketing_spend_per_user'] > upper)
][['customer_id', 'marketing_spend_per_user']]

Empty DataFrame
Columns: [customer_id, marketing_spend_per_user]
Index: []

In [58]:
Q1 = df['lifetime_value'].quantile(0.25)
Q3 = df['lifetime_value'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 741.3012511803968
Q3: 1677.8603988008174
IQR: 936.5591476204206
Lower: -663.537470250234
Upper: 3082.6991202314484

In [59]:
df[
    (df['lifetime_value'] < lower) |
    (df['lifetime_value'] > upper)
][['customer_id', 'lifetime_value']]

       customer_id  lifetime_value
159          10160     3277.496994
487          10488     3195.135529
673          10674     3720.746072
715          10716     3184.428275
1474         11475     3121.827976
2049         12050     3564.050153
2517         12518     3222.181203
2800         12801     3141.066305
2974         12975     3463.434378
3237         13238     3500.622066
3577         13578     3242.012795
3782         13783     3301.136544
4448         14449     3222.066488
4515         14516     3767.490455
4707         14708     3117.978757
5419         15420     3110.307591
6161         16162     3505.180570
6186         16187     3124.075836
6338         16339     3400.089504
6541         16542     3350.918886
6601         16602     3083.732546
6657         16658     3093.953509
6664         16665     3386.093546
6717         16718     3141.057916
7824         17825     3252.042872
8496         18497     3281.026762
8856         18857     3202.279786
9057         19058     3116.163204
9271         19272     3393.347513
9660         19661     3092.145552
9857         19858     3166.215371
10092        20093     3146.957059
10210        20211     3352.730035
10390        20391     3354.779920
10500        20501     3262.376974
10664        20665     3133.951656
10833        20834     3512.206539
11065        21066     3374.040333
11656        21657     3326.640422
11716        21717     3135.752005
11768        21769     3546.179140
11777        21778     3128.993406
11930        21931     3289.059582
11977        21978     3171.959519
11983        21984     3248.128146
12258        22259     3298.305550
12507        22508     3138.510132
13215        23216     3167.577004
13446        23447     3106.919543
13630        23631     3368.791826
13648        23649     3285.443438
13864        23865     3168.890247
13932        23933     3180.163556
14434        24435     3404.874473
14773        24774     3267.267540
14875        24876     3678.145232

In [60]:
df[
    (df['lifetime_value'] < lower) |
    (df['lifetime_value'] > upper)
].shape[0]

56

In [61]:
Q1 = df['last_3_month_purchase_freq'].quantile(0.25)
Q3 = df['last_3_month_purchase_freq'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Q1:", Q1)
print("Q3:", Q3)
print("IQR:", IQR)
print("Lower:", lower)
print("Upper:", upper)

Q1: 3.0
Q3: 11.0
IQR: 8.0
Lower: -9.0
Upper: 23.0

In [62]:
df[
    (df['last_3_month_purchase_freq'] < lower) |
    (df['last_3_month_purchase_freq'] > upper)
][['customer_id', 'last_3_month_purchase_freq']]

Empty DataFrame
Columns: [customer_id, last_3_month_purchase_freq]
Index: []

## 4.Duplicate Records

In [63]:
df.duplicated().sum()

np.int64(0)

## 5. Date Consistency

In [64]:
df[['signup_date', 'last_purchase_date']].dtypes

signup_date           object
last_purchase_date    object
dtype: object

In [65]:
df['signup_date'] = pd.to_datetime(df['signup_date'])
df['last_purchase_date'] = pd.to_datetime(df['last_purchase_date'])

In [66]:
df[['signup_date', 'last_purchase_date']].dtypes

signup_date           datetime64[ns]
last_purchase_date    datetime64[ns]
dtype: object

### Signup Date vs Last Purchase Date

In [67]:
df[df['last_purchase_date'] < df['signup_date']][
    ['customer_id', 'signup_date', 'last_purchase_date']
]

       customer_id signup_date last_purchase_date
1            10002  2024-06-16         2024-05-07
3            10004  2024-01-28         2023-05-20
5            10006  2024-05-08         2023-01-20
12           10013  2023-03-14         2023-01-25
13           10014  2024-09-14         2023-01-31
...            ...         ...                ...
14973        24974  2023-10-17         2023-10-02
14974        24975  2024-08-14         2023-05-21
14976        24977  2024-03-30         2023-11-03
14986        24987  2024-02-20         2023-05-21
14988        24989  2024-09-04         2023-07-10

[3762 rows x 3 columns]

In [68]:
(df['last_purchase_date'] < df['signup_date']).sum()

np.int64(3762)

In [69]:
print("Signup date range:")
print(df['signup_date'].min(), "to", df['signup_date'].max())

print("\nLast purchase date range:")
print(df['last_purchase_date'].min(), "to", df['last_purchase_date'].max())

Signup date range:
2022-01-01 00:00:00 to 2024-09-26 00:00:00

Last purchase date range:
2023-01-01 00:00:00 to 2025-03-10 00:00:00

In [70]:
df['date_difference'] = (
    df['signup_date'] - df['last_purchase_date']
).dt.days

df[df['date_difference'] > 0]['date_difference'].describe()

count    3762.000000
mean      211.450558
std       152.064437
min         1.000000
25%        83.000000
50%       183.000000
75%       318.000000
max       627.000000
Name: date_difference, dtype: float64

In [71]:
df[df['date_difference'] > 0]['signup_date'].dt.year.value_counts().sort_index()

signup_date
2023    1250
2024    2512
Name: count, dtype: int64

In [72]:
df[df['date_difference'] > 0]['signup_date'].dt.to_period('M').value_counts().sort_index()

signup_date
2023-01      5
2023-02     31
2023-03     31
2023-04     52
2023-05     80
2023-06     96
2023-07    120
2023-08    144
2023-09    139
2023-10    153
2023-11    194
2023-12    205
2024-01    231
2024-02    230
2024-03    246
2024-04    236
2024-05    300
2024-06    315
2024-07    316
2024-08    313
2024-09    325
Freq: M, Name: count, dtype: int64

In [73]:
df[df['date_difference'] > 300][
    ['customer_id', 'signup_date', 'last_purchase_date', 'date_difference']
].head(20)

     customer_id signup_date last_purchase_date  date_difference
5          10006  2024-05-08         2023-01-20              474
13         10014  2024-09-14         2023-01-31              592
32         10033  2024-03-30         2023-02-05              419
42         10043  2024-06-29         2023-06-15              380
56         10057  2024-07-29         2023-04-16              470
74         10075  2024-06-02         2023-06-28              340
83         10084  2024-09-16         2023-08-13              400
88         10089  2024-02-19         2023-02-19              365
99         10100  2024-05-18         2023-07-20              303
101        10102  2024-03-04         2023-04-08              331
116        10117  2024-04-13         2023-02-28              410
234        10235  2024-05-26         2023-07-15              316
240        10241  2024-08-28         2023-05-15              471
267        10268  2024-08-25         2023-04-15              498
326        10327  2024-04-22         2023-02-11              436
342        10343  2024-08-17         2023-07-27              387
358        10359  2024-08-28         2023-08-17              377
365        10366  2024-07-29         2023-06-15              410
384        10385  2024-08-04         2023-04-12              480
391        10392  2024-06-14         2023-08-16              303

In [74]:
df[df['date_difference'] > 300][
    ['customer_id', 'signup_date', 'last_purchase_date',
     'total_visits', 'total_spent']
].head(20)

     customer_id signup_date last_purchase_date  total_visits  total_spent
5          10006  2024-05-08         2023-01-20            13   423.243551
13         10014  2024-09-14         2023-01-31            11   173.408948
32         10033  2024-03-30         2023-02-05            19   706.643292
42         10043  2024-06-29         2023-06-15            19   498.843859
56         10057  2024-07-29         2023-04-16            21   132.133273
74         10075  2024-06-02         2023-06-28            11   678.222823
83         10084  2024-09-16         2023-08-13            16   445.382747
88         10089  2024-02-19         2023-02-19            17   295.108330
99         10100  2024-05-18         2023-07-20            23   664.148552
101        10102  2024-03-04         2023-04-08            14   642.845717
116        10117  2024-04-13         2023-02-28            19  1024.837307
234        10235  2024-05-26         2023-07-15            21   222.899383
240        10241  2024-08-28         2023-05-15             8     8.150370
267        10268  2024-08-25         2023-04-15            14   702.304769
326        10327  2024-04-22         2023-02-11            20   732.127479
342        10343  2024-08-17         2023-07-27            13   685.361312
358        10359  2024-08-28         2023-08-17            13   353.996148
365        10366  2024-07-29         2023-06-15            17   366.707213
384        10385  2024-08-04         2023-04-12            16   498.843859
391        10392  2024-06-14         2023-08-16            13    99.510503

## 6. Data Types

In [75]:
df.dtypes

customer_id                            int64
gender                                object
age                                  float64
country                               object
city                                  object
signup_date                   datetime64[ns]
last_purchase_date            datetime64[ns]
acquisition_channel                   object
device_type                           object
subscription_type                     object
is_premium_user                        int64
total_visits                           int64
avg_session_time                     float64
pages_per_session                    float64
email_open_rate                      float64
email_click_rate                     float64
total_spent                          float64
avg_order_value                      float64
discount_used                          int64
coupon_code                           object
support_tickets                        int64
refund_requested                       int64
delivery_delay_days                    int64
payment_method                        object
satisfaction_score                   float64
nps_score                              int64
marketing_spend_per_user             float64
lifetime_value                       float64
last_3_month_purchase_freq             int64
churn                                  int64
date_difference                        int64
dtype: object

In [76]:
df.drop(columns='date_difference', inplace=True)

In [77]:
'date_difference' in df.columns

False

## 7. Final Data Validation

In [78]:
df.shape

(15000, 30)

In [79]:
df.isna().sum()

customer_id                   0
gender                        0
age                           0
country                       0
city                          0
signup_date                   0
last_purchase_date            0
acquisition_channel           0
device_type                   0
subscription_type             0
is_premium_user               0
total_visits                  0
avg_session_time              0
pages_per_session             0
email_open_rate               0
email_click_rate              0
total_spent                   0
avg_order_value               0
discount_used                 0
coupon_code                   0
support_tickets               0
refund_requested              0
delivery_delay_days           0
payment_method                0
satisfaction_score            0
nps_score                     0
marketing_spend_per_user      0
lifetime_value                0
last_3_month_purchase_freq    0
churn                         0
dtype: int64

In [80]:
for col in count_cols:
    print(f"\n{col}")
    print(df[df[col] <= 0][['customer_id', col]])

total_visits
Empty DataFrame
Columns: [customer_id, total_visits]
Index: []

last_3_month_purchase_freq
       customer_id  last_3_month_purchase_freq
13           10014                           0
26           10027                           0
39           10040                           0
40           10041                           0
47           10048                           0
...            ...                         ...
14955        24956                           0
14960        24961                           0
14973        24974                           0
14994        24995                           0
14996        24997                           0

[1018 rows x 2 columns]

pages_per_session
Empty DataFrame
Columns: [customer_id, pages_per_session]
Index: []

In [81]:
df[df['age'] <= 0][['customer_id', 'age']]

Empty DataFrame
Columns: [customer_id, age]
Index: []

In [82]:
df[df['avg_session_time'] <= 0][['customer_id', 'avg_session_time']]
df[df['pages_per_session'] <= 0][['customer_id', 'pages_per_session']]

Empty DataFrame
Columns: [customer_id, pages_per_session]
Index: []

In [83]:
df[(df['email_open_rate'] < 0) | (df['email_open_rate'] > 100)][['customer_id', 'email_open_rate']]

df[(df['email_click_rate'] < 0) | (df['email_click_rate'] > 100)][['customer_id', 'email_click_rate']]

Empty DataFrame
Columns: [customer_id, email_click_rate]
Index: []

In [84]:
df[df['total_spent'] < 0][['customer_id', 'total_spent']]
df[df['avg_order_value'] < 0][['customer_id', 'avg_order_value']]
df[df['marketing_spend_per_user'] < 0][['customer_id', 'marketing_spend_per_user']]
df[df['lifetime_value'] < 0][['customer_id', 'lifetime_value']]

Empty DataFrame
Columns: [customer_id, lifetime_value]
Index: []

In [85]:
df[(df['satisfaction_score'] < 0) | (df['satisfaction_score'] > 10)][['customer_id', 'satisfaction_score']]

df[(df['nps_score'] < -100) | (df['nps_score'] > 100)][['customer_id', 'nps_score']]

Empty DataFrame
Columns: [customer_id, nps_score]
Index: []

### Cleaned dataset

In [86]:
clean_df = pd.read_csv(r"C:\Users\hp\Downloads\Sales_Marketing_Dataset\clean_customer_data.csv")

clean_df.shape

(15000, 30)

In [87]:
import os

os.path.exists(r"C:\Users\hp\Downloads\Sales_Marketing_Dataset\clean_customer_data.csv")

True